server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database

keycloak:
  realm: javatechie
  auth-server-url: http://localhost:8180
  resource: springboot-keycloak
  public-client: true
  bearer-only: true